### ISSUE TITLE
compiler/checker: panic on build when using import rename

### ISSUE THREAD

**Issue by traetox** [open2b/scriggo#904]
When a package is imported using the `AS` keyword to change the import path scriggo does not detect that the package name is not the path.  This allows the script to reference the wrong package name and panic the program during the `Build` call.

Scriggo command  and library version: `scriggo version v0.53.1 (go1.16.7)`

## The Scriggofile
```
SET PACKAGE main
SET VARIABLE packages
GOOS linux

IMPORT github.com/google/uuid
IMPORT github.com/3dsinteractive/uuid as foobar
```
## The main.go file
```
package main

import (
        "github.com/open2b/scriggo"
        "github.com/open2b/scriggo/native"
)

var packages native.Packages

func main() {

        // src is the source code of the program to run.
        src := []byte(`
        package main

        import (
                "github.com/google/uuid"
                "foobar"
        )

        func main() {
            println(uuid.New().String())
            println(foobar.New().String())
        }
    `)

        // Create a file system with the file of the program to run.
        fsys := scriggo.Files{"main.go": src}

        // Use the importer in the packages variable.
        opts := &scriggo.BuildOptions{Packages: packages}

        // Build the program.
        program, err := scriggo.Build(fsys, opts)
        if err != nil {
                panic(err)
        }

        // Run the program.
        if err = program.Run(nil); err != nil {
                panic(err)
        }
}
```

## The panic
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5582c5]

goroutine 1 [running]:
github.com/open2b/scriggo/internal/compiler.checkPackage.func1(0xc00014bb80)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/internal/compiler/checker_package.go:523 +0x8d
panic(0x6e0100, 0x8f5290)
        /opt/go/go/src/runtime/panic.go:965 +0x1b9
github.com/open2b/scriggo/ast.(*Identifier).Pos(0x0, 0x6edfe0)
        <autogenerated>:1 +0x5
github.com/open2b/scriggo/internal/compiler.checkError(0x71b1eb, 0x4, 0x6edfe0, 0x0, 0xc000068070, 0x64, 0x0, 0x0, 0x0, 0x4, ...)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/internal/compiler/checker.go:350 +0x1a3
github.com/open2b/scriggo/internal/compiler.(*typechecker).errorf(...)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/internal/compiler/checker.go:344
github.com/open2b/scriggo/internal/compiler.(*typechecker).assignScope(0xc00014c000, 0x71b377, 0x4, 0xc0001517a0, 0x0, 0xc000026240)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/internal/compiler/checker.go:264 +0x590
github.com/open2b/scriggo/internal/compiler.(*typechecker).checkImport(0xc00014c000, 0xc000026240, 0x0, 0x0)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/internal/compiler/checker_statements.go:1020 +0x1b57
github.com/open2b/scriggo/internal/compiler.checkPackage(0xc000119180, 0xc0000261c0, 0x71b1eb, 0x4, 0x78bb20, 0xc00007e690, 0x1, 0x0, 0x0, 0x0, ...)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/internal/compiler/checker_package.go:572 +0x11eb
github.com/open2b/scriggo/internal/compiler.typecheck(0xc000026180, 0x78bb20, 0xc00007e690, 0x1, 0x0, 0x0, 0x0, 0x0, 0x418f7e, 0x7fbfb08ef300, ...)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/internal/compiler/checker.go:47 +0xffa
github.com/open2b/scriggo/internal/compiler.BuildProgram(0x78ba80, 0xc00007e720, 0x0, 0x0, 0x0, 0x78bb20, 0xc00007e690, 0x0, 0x0, 0x8ff160, ...)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/internal/compiler/compiler.go:140 +0x11d
github.com/open2b/scriggo.Build(0x78ba80, 0xc00007e720, 0xc000053f38, 0x7, 0xc000126088, 0xc000000180)
        /home/kris/mygo/pkg/mod/github.com/open2b/scriggo@v0.53.1/programs.go:98 +0xd9
```

### Note

If the script sets the package name then the program executes normally

e.g. `import foobar "foobar"`

**Comment by traetox** [comment]
I feel like i have a decent handle on that process now, at the risk of loading up too much stuff in this: https://github.com/open2b/scriggo/pull/905 I could tackle the package renaming too.

Let me know if you want to prevent too much "stuff" in a single PR.

**Comment by traetox** [comment]
definitely a dup of https://github.com/open2b/scriggo/issues/881, closing.
